name: Deploy Vite Website to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code.
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup Node.js environment.
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install project dependencies.
      - name: Install Dependencies
        run: npm install

      # Build the Vite project (ensure your package.json has a build script).
      - name: Build Project
        run: npm run build

      # Deploy the build output to the gh-pages branch.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
